DiscussionApp/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
]

forum/urls.py
from django.urls import path
from . import views


app_name = 'forum'
urlpatterns = [
    path('', views.index, name='home'),
    path('<slug:slug>/', views.post_detail, name='post_detail'),    #post detail view for viewing post using slug
    path('search' , views.search, name='search'),
    path('login' , views.login_view, name='login'),
    path('logout' , views.logout_view, name='logout'),
    path('signup' , views.signup_view, name='signup'),
    path(r'^upvote/<int:id>/$' , views.upvote , name='upvote'),
    path(r'^solved/<slug:slug>/$' , views.solved , name='solved'),
    path(r'^category/<int:id>/$' , views.category_view , name='category'),
    path(r'^subcategory/<int:id>/$' , views.sub_category_view , name='subcategory'),
    path(r'^answer/<slug:slug>/$' , views.answer_view , name='answer'),
    path('post_question' , views.post_question , name='post_question'),
    path('notifications' , views.notification_view , name='notifications'),
    path('recommended_to_answer', views.recommend_questions , name='recommended_to_answer'),
    path('my_questions' , views.my_questions , name='my_questions'),
     path('<slug>/delete/', views.PostDeleteView.as_view() , name="delete_post"),
]

forum/forms.py
from django import forms

from . import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class Create_user_form(UserCreationForm):
    GENDER_CHOICES = [('M','Male'),('F','Female')]
    first_name = forms.CharField(max_length=50, required=True)
    last_name = forms.CharField(max_length=50, required=True)
    gender = forms.ChoiceField(choices=GENDER_CHOICES,widget=forms.RadioSelect)
    

    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password1','password2','gender']

        widgets = {
            'username' :forms.TextInput(attrs ={'name':'username','class':'form-item'})  ,
            'email' :forms.EmailInput(attrs ={'name':'email','class':'form-item'}),
            'password1' :forms.PasswordInput(attrs ={'name':'password','class':'form-item'}),
            'first_name' :forms.TextInput(attrs ={'name':'firstname','class':'form-item'}),
            'last_name' :forms.TextInput(attrs ={'name':'lastname','class':'form-item'}),
        }


    def clean(self):
        all = super().clean()
        email = all['email']
        gender = all['gender']
        username = all['username']
        
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("Username already taken , choose another")
        if User.objects.filter(email = email).exists():
            raise forms.ValidationError(str(email) + " is already used , use another")
        if gender not in ['M', 'F']:
            raise forms.ValidationError("Gender error , don't tamper with data")

class PostQuestionForm(forms.ModelForm):

    class Meta:
        model = models.Post
        fields = ['title','category','subcategory']

        widgets = {
            'title' :forms.TextInput(attrs ={'name':'title'}),
            'category' :forms.Select(attrs ={'name':'category'}),
            'subcategory' :forms.Select(attrs ={'name':'subcategory'}),
        }

forum/views.py
from unicodedata import category
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate , login , logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import DeleteView
from django.contrib.auth.models import User
from django.http import Http404, HttpResponseRedirect
from . import models
from . import forms
from . import recommendmodel as recommend
from . import advanced_search 
import os

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, 'Welcome,{}'.format(username))
            return redirect('forum:home')
        else:
            messages.error(request, 'Something wrong with your username or password')
            return redirect('forum:login')
    else:

        return render(request, 'forum/login.html')

def signup_view(request):
    form = forms.Create_user_form(request.POST or None)
    if form.is_valid():
        user = form.save()
        user.refresh_from_db()
        user = User.objects.get(username=form.cleaned_data.get('username'))
        profile = models.Profile(user=user)
        profile.first_name = form.cleaned_data['first_name']
        profile.last_name = form.cleaned_data['last_name']
        profile.gender = form.cleaned_data['gender']
        profile.save()
        form = forms.Create_user_form()
        messages.success(request, 'Account created successfully')
        redirect('forum:login')
    
    context = {
        'form' : form
    }
    return render(request, 'forum/signup.html',context=context)

def logout_view(request):
    logout(request)
    messages.success(request, 'You have been logged out')
    return redirect('forum:home')


class PostDeleteView(DeleteView):
    
    model = models.Post
    success_url ="/"
    template_name = "forum/post_confirm_delete.html"
    def get_object(self):
        obj = super().get_object()
        if not obj.posted_by == self.request.user:
            raise Http404
        return obj
    def delete(self, request, *args, **kwargs):
        messages.success(request, 'Post Deleted')
        return super().delete(request, *args, **kwargs)

def index(request): #home page of discussion forum
    categories = models.Category.objects.all()
    posts = models.Post.objects.order_by('-posted_on','views')

    select = dict()
    for i in categories:
        select[i.name] = [j.name for j in i.subcategory.all()]
    

    if request.user.is_authenticated:
        user = User.objects.filter(username=request.user.username).first()
        profile = models.Profile.objects.filter(user=user).first()
        if profile.prefered_categories.all().__len__() != 0:
            posts = posts.filter(category__in=profile.prefered_categories.all())

    context = {
        'categories': categories,
        'posts': posts,
        'selects':select,
        
    }
    return render(request, 'forum/index.html' , context=context)


def recommend_questions(request):
    user = request.user
    pref_sub = user.profile.prefered_categories.all()
    posts = models.Post.objects.filter(solved=False)
    posts_solved = models.Post.objects.filter(category__in = pref_sub)
    context = {
        'posts':posts,
        'solved_posts':posts_solved,

    }
    return render(request, "forum/question_recommend.html",context = context)

def my_questions(request):
    user = request.user
    
    posts = models.Post.objects.filter(posted_by=user)
    #posts_solved = models.Post.objects.filter(user=user)
    context = {
        'posts':posts,
        

    }
    return render(request, "forum/my_questions.html",context = context)

def post_detail(request, slug): #post detail view for viewing post using slug
    post = models.Post.objects.filter(slug=slug).first()
    post.views += 1
    post.save()
    
    '''recommended = recommend.recommend_pro(int(post.id))
    recommended = recommended[:]
    recommended_posts = models.Post.objects.filter(id__in=recommended)
    print(recommended)'''
    
    try:
        recommended = recommend.recommend_pro(int(post.id))
        recommended = recommended[:]
        recommended_posts = models.Post.objects.filter(id__in=recommended)
        print(recommended)
    except :
        recommended_posts = []
        rp= models.Post.objects.all()
        for i in rp:
            if i.category.name == post.category.name:
                if i.slug != post.slug:
                    recommended_posts.append(i)
    

    if request.user.is_authenticated:
        
        user = User.objects.filter(username=request.user.username).first()
        
        profile = models.Profile.objects.filter(user=user).first()
        print("--------"+ profile.first_name)
        if post.category not in profile.prefered_categories.all():
            profile.prefered_categories.add(post.category) #.remove(post.category) to remove
            profile.save()
            
    context = {
        'post': post,
        'answers': post.answer.all().order_by('-upvotes'),
        'recommended_posts': recommended_posts[:3],
    }
    return render(request, 'forum/post.html', context=context)

def search(request):
    if request.method == 'GET':
        query = request.GET['q']
        if query:
            terms = advanced_search.search(query)
            posts_list = set()
            for i in terms:
                all_res = models.Post.objects.filter(title__icontains=i)
                
                for j in all_res:
                    posts_list.add(j)
                
                try:
                    all_cat = models.Category.objects.filter(name__icontains=i).first()
                    cat = all_cat.post_category.all()
                    for k in cat:
                        posts_list.add(k)
                except:
                    pass
            posts = list(posts_list)
            if posts.__len__() == 0:
                messages.error(request, 'Enter a valid search query')
                return redirect('forum:home')
            context = {
                'posts': posts,
                'query': query,
            }
            return render(request, 'forum/search.html', context=context)
    messages.error(request, 'You have to enter a search query')
    return redirect('forum:home')

def category_view(request,id):
    categories = models.Category.objects.filter(id=id).first()
    post = categories.post_category.all()
    
    context = {
        'posts': post,
        'category': categories,
    }
    return render(request, 'forum/category.html', context=context)
def sub_category_view(request,id):
    categories = models.SubCategory.objects.filter(id=id).first()
    post = categories.post_sub_category.all()
    
    context = {
        'posts': post,
        'category': categories,
    }
    return render(request, 'forum/category.html', context=context)

def upvote(request,**kwargs):
    answer = models.Answer.objects.get(id=kwargs['id'])
   
    post = answer.post
    if request.user.is_authenticated:
       
        user = User.objects.filter(username=request.user.username).first()
        
        profile = models.Profile.objects.filter(user=user).first()
        
        if post.category not in profile.prefered_categories.all():
            profile.prefered_categories.add(post.category) #.remove(post.category) to remove
            profile.save()
    if models.Upvote.objects.filter(answer=answer , user=user).exists():
        pass
    else:
        upv = models.Upvote(user=user, answer=answer)
        upv.save()
    
    messages.success(request,"{}, thanks for upvoting".format(request.user.username))
    return redirect('forum:post_detail',slug=post.slug)

def solved(request,slug):
    post = models.Post.objects.get(slug=slug)
    if(not post.solved):
        post.solved = True
    else:
        post.solved = False
    post.save()
    return redirect('forum:post_detail',slug=slug)


def answer_view(request,slug):
    
    post = models.Post.objects.get(slug=slug)
    if request.method == 'POST':
        answer = request.POST['answer']
        
        if answer:
            ans = models.Answer(posted_by=request.user, post=post, answer=answer)
            ans.save()
            notify = models.Notification(post=post, answer=ans,to_user=post.posted_by)
            notify.save()
            messages.success(request, 'Answer posted successfully')
            #os.system("python systemUtils.py")
            return redirect('forum:post_detail', slug=slug)
        messages.error(request, 'You have to enter an answer')
    return redirect('forum:post_detail', slug=slug)

@login_required
def notification_view(request):
    noti = models.Notification.objects.filter(to_user=request.user).order_by('-on')
    context= {'notifications':noti}
    return render(request, 'forum/notifications.html',context=context)


@login_required
def post_question(request):
    category_list = models.Category.objects.all()
    sub = models.SubCategory.objects.all()
    if request.method == 'POST':
        question = request.POST['question']
        category = request.POST['category']
        sub_category = request.POST['sub_category']
        if question and category:
            for  i in category_list:
                if i.name == category:
                    cat = i
            for i in sub:
                if i.name == sub_category:
                    sub_cat = i
            post = models.Post(posted_by=request.user, title=question, category=cat, subcategory=sub_cat)
            post.save()
            messages.success(request, 'Question posted successfully')
            #os.system("python systemUtils.py")
            return redirect('forum:post_detail', slug=post.slug)

forum/templates/forum/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" href="{% static "forum/images/main.png" %}">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/cec955fd83.js" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
   <!-- <link rel="stylesheet" href="css/all.min.css"> -->
    <link rel="stylesheet" href="{% static "forum/css/base.css" %}">
    {% block css %} {% endblock css %}

    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
     
    <!-----------Nav bar----------------------------->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark  bg-prime" id="header">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a class="nav-link" href={% url "forum:home" %}><i style="color: white;"class="fas fa-home nav"></i>
                  
                </a>
              </li>
              <li class="nav-item">
                 {% if user.is_authenticated %}
                <a class="nav-link" href={% url "forum:notifications" %}><i  style="color: white;"class="fas fa-bell nav"></i></a>
                {% else %}
                <a class="nav-link" href={% url "forum:login" %}><i  style="color: white;"class="fas fa-bell nav"></i></a>
                {% endif %}

              
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link" href={% url "forum:recommended_to_answer" %}><i  style="color: white;"class="fas fa-comments nav"></i></a>
                {% else %}
                <a class="nav-link" href={% url "forum:login" %}><i  style="color: white;"class="fas fa-comments nav"></i></a>
                {% endif %}
              </li>
              
              <form class="form-inline top" action="{% url "forum:search" %}" method="get">
                <input class="form-control mr-sm-2 search-box-nav" style="margin-right: 5px; border-radius: 15px;color: #ff5e62;width:max-content;" type="text" placeholder="Search" aria-label="Search" name="q">
                <button class="btn search btn-outline-primary my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
              </form>

                <li class="nav-item dropdown" style="position: absolute;right: 0;margin-left: auto;">
                      <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i style="color: white;" class="fas fa-user nav"></i></a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
  
                              
  
                            {% if user.is_authenticated %}
                              <a class="dropdown-item" href={% url "forum:logout" %}>Sign Out</a>
                            {% else %}
                              <a class="dropdown-item" href={% url "forum:login" %}>Sign In</a>
                              <a class="dropdown-item" href={% url "forum:signup" %}>Signup</a>
                            {% endif %}
                              
  
                              <div class="dropdown-divider"></div>
                              {% if user.is_authenticated %}
                                <a class="dropdown-item" href={% url "forum:my_questions" %}>My Questions</a>
                              
                              {% endif %}
                              
                                
                      </div>
                  </li>
            </ul>
            
             
          </div>
        </div>
      </nav>


    <!-----------End of Nav Bar----------------------------->
      

    <div class="container">
      <!-----------left-sidebar----------------------------->
      <div class="left-sidebar">
        <div class="imp-links">
         
         {% block categories %}
         {% endblock categories %}

        </div>
      </div>
      <!-----------main-content----------------------------->
      <div class="main-content">
       
     
        
      {% block content %} {% endblock content %}
      
   
      </div>
    
     

 {% block scripts %} {% endblock scripts %}
  <script src="{% static "forum/js/jquery.min.js" %}"> </script>
  <script src="{% static 'forum/js/jquery-3.5.1.min.js' %}"></script>

  </body>
</html>

forum/templates/forum/category.html
{% extends "forum/base.html" %}

    
    {% load bootstrap4 %}
    {% load static %}
    
    {% block title %}{{ category.name }}{% endblock title %}



    {% block content %}
    {% bootstrap_messages %} 
    <h2>Search Result</h2>
    {% for post in posts %}
<div class="question-container">
    <p style="color: #303030; margin-bottom: 0px;" ><i class="fas fa-user-circle" style="margin: 5px; font-size: large;"></i>{{ post.posted_by }}</p>
    <h5 style="color: blue; padding-left: 3px;"><a href={% url "forum:post_detail" slug=post.slug %}>{{ post.title }}</a>
      {% if post.solved %}
      <em style="color:green;">Solved</em>
  {% else %}
      <em style="color:red;">Unsolved</em>
  {% endif %}</h5>
    <p style="color: #acacac; padding-left: 3px;">
      {{ post.answerCount }} 
      {% if post.answerCount > 1 %}  answers
      {% else %}  answer
      {% endif %}
  </p>
  </div>
  {% endfor %}
    {% endblock content %}

forum/templates/forum/index.html
{% extends "forum/base.html" %}
{% load bootstrap4 %}
{% load static %}
{% block css %} 
<link rel="stylesheet" href={% static "forum/css/index.css" %}>
<style>
    .full-screen{
        position: absolute;
        top:0;
          left:0;
          right:0;
          bottom:0;
          background-color: #ffffff98;
          z-index: 22;
          backdrop-filter: blur(6px);
          -webkit-backdrop-filter: blur(10px);
          -moz-backdrop-filter: blur(10px);
          transition:2s ease-in-out;
         
    }
    
    .flex-container-center
    {
        display:none;
        flex-direction:column;
        justify-content: center;
        align-items: center;
        transition: all 2s ease-in-out;
        
    }
    
    .Cancel
    {
        position: absolute;
        right:0;
        top:0;
        margin-left: auto;
        margin-right: 5px;
        margin-top: 5px;
        border-radius: 40px;
        transition: 00.4s ease-in-out;
    
    }
    .Cancel:hover
    {
        border-radius: 5px;
        transform: scale(1.1);
    }
    
    .answer-form
    {
        background-color:rgba(255, 255, 255);
        width: 60%;
        height:45%;
        position: relative;
        border-radius: 5px;
        box-shadow: 5px 5px 8px -4px #888888;
        padding-left:20px;
        
    }
    .answer-form-grp
    {
        display:flex;
        flex-direction:column;
        justify-content: center;
        align-items: center !important;
    }
    
    .ans-submit
    {
        margin-top: 15px;
        background-image:linear-gradient(120deg,#fc874d,#ff3d41) ;
        border:none;
        border-radius :5px;
        transition: 0.2s ease-in;
        }
    
    .ans-submit:hover
    {
        border-radius: 10px;
        transform: scale(1.1);
        background-image:linear-gradient(120deg,#fc935f,#fc6164) ;
    }
    .form-control-submit
    {
        margin-top: 50px;
    }
</style>
{% endblock css %}
{% block title %}Home{% endblock title %}



{% block categories %}
<h5 style="color: #acacac; font-family: Verdana, Geneva, Tahoma, sans-serif ;">By Categories</h5>
<ul class="list-group" style="width:60%;">
{% for category in categories %}
    <li class="list-group-item list-group-item-action cat">
    <a href={% url "forum:category" id=category.id %}>{{ category.name }}</a>
    <ul class="list-group list-group-flush sub-cat">
    {% for subcat in category.subcategory.all %}
            <li class="list-group-item list-group-item-action list-group-item-light" style="display:none;"> <a href={% url "forum:subcategory" id=subcat.id %}>{{ subcat.name }}</a></li>
    {% endfor %}
    </ul>
    </li>
{% endfor %}
</ul>

{% endblock categories %}



{% block content %}
{% bootstrap_messages %}
<div class="search-box">
    {% if user.is_authenticated %}
    <input type="Button" name="ask" value="What do you want to ask?" class="btn btn-outline-primary main-btn" onclick="togglepop()"> 
    {% else %}
    <input type="Button" name="ask" value="Please Login to ask" class="btn btn-outline-primary main-btn" onclick="location.href='{% url "forum:login" %}'"> 
    {% endif %}
    
</div>
<br>
<br>

<h6 >What's Trending <i class="fas fa-fire" style="color: #e25822;"></i></h6>
{% for post in posts %}
<div class="question-container" style="">
    <p style="color: #303030; margin-bottom: 0px;" ><i class="fas fa-user-circle" style="margin: 5px; font-size: large;"></i>{{ post.posted_by }} </p>
    <h5 style="color: blue; padding-left: 3px;"><a href={% url "forum:post_detail" slug=post.slug %}>{{ post.title }}</a>
        {% if post.solved %}
        <em style="color:green;">Solved</em>
    {% else %}
        <em style="color:red;">Unsolved</em>
    {% endif %}</h5>
    <p style="color: #acacac; padding-left: 3px;">
        {{ post.answerCount }} 
        {% if post.answerCount > 1 %}  answers
        {% else %}  answer
        {% endif %}
        
    </p>
  </div>
  {% endfor %}

 
{% if user.is_authenticated %}
<div class="full-screen flex-container-center">
    <div class="answer-form">
    <h2 style="justify-content:center;align-item:center;display:flex;">Ask Something</h2>
    <form action={% url "forum:post_question" %} class="container" method="POST">
        {% csrf_token %}
        <div class="answer-form-grp">
        <input type="text" name="question" placeholder="Write your question here...." class="form-control form-control-submit" size="100"> 
        <div class="input-group mb-3" style="margin-top:15px;">
            <select class="form-select category" id="inputGroupSelect01" name="category">
              <option selected value="None">Categories...</option>
              {% for category in categories %}
              <option value="{{ category.name }}">{{ category.name }}</option>
              {% endfor %}
            </select>
          </div> 
          <div class="input-group mb-3">
            <select class="form-select subcategory" id="inputGroupSelect01 subcategory" name="sub_category">
              <option selected value="None">SubCategory..</option>
            </select>
          </div> 
        <button type="submit" class="btn btn-success ans-submit">Submit</button>
         <button type="button" class="btn btn-outline-danger Cancel" onclick="togglepop()">X</button>
         </div>
    </form> 
    </div>
</div>
{% endif %}

{% endblock content%}


{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <script>
      var cats = document.querySelectorAll('.cat')
        for(var i=0;i<cats.length;i++){
            cats[i].addEventListener('mouseover',function(){
                var subcats = this.querySelectorAll('.sub-cat li')
                for(var j=0;j<subcats.length;j++){
                    subcats[j].style.display = 'block'
                }
            })
        }
        for(var i=0;i<cats.length;i++){
            cats[i].addEventListener('mouseout',function(){
                var subcats = this.querySelectorAll('.sub-cat li')
                for(var j=0;j<subcats.length;j++){
                    subcats[j].style.display = 'none'
                }
            })
        }
    
     
  </script>

  <script> 
    function togglepop(question,answer) {
        var x = document.querySelector(".flex-container-center-fs");
        if (x.style.display === "none") {
            document.querySelector(".pop-text").innerHTML = "= "+answer;
            document.querySelector(".pop-ques").innerHTML = question;
            x.style.display = "flex";
        } else {
            x.style.display = "none";
        }
    }
    </script>
    <script> 
        function togglepop() {
            var x = document.querySelector(".flex-container-center");
            if (x.style.display === "none") {
                x.style.display = "flex";
            } else {
                x.style.display = "none";
            }
        }
        </script>
        <script>
           var cat =document.querySelector(".category");
           var sub = document.querySelector(".subcategory");
           cat.addEventListener('change',function()
           {   var val = cat.value;
                
            sub.innerHTML = '';

                var context = {{ selects|safe }};

                var con = context[val];
                for (var i=0;i<con.length;i++)
                {
                    sub.innerHTML += '<option value='+context[val][i]+'>'+ context[val][i] + '</option\>';
                }

                
                
                

                    /*
                var context = {{ selects|safe }};
                var fin='';
                for(val i=0;i< context[val].length;i++)
                {
                    sub.innerHTML=  '<option value="'+context[val][i] +'">'+context[val][i]+'</option>';
                }

                sub.innerHTML=  '<option value="'+context[val][0] +'">'+context[val][i]+'</option>';
                */
                 
                

                
               /*sub.innerHTML = '
               <option selected>Sub Categories...</option\>'+
               '{% for i in '+ val +'.subcategories.all %\}
               <option value="{{ i.name }}">{{ i.name }}</option\>
               {% endfor %\}
               ';*/

           });
        </script>
{% endblock %}

forum/templates/forum/login.html
{% extends "forum/base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block css %} <link rel="stylesheet" href={% static "forum/css/login.css" %}>{% endblock css %}

{% block title %}
Login
{% endblock title %}


{% block content %}
    {% bootstrap_messages %}
   <div class = "center" >
        <h1>Login</h1>
        <form action="{% url "forum:login" %}" method="POST">
            {% csrf_token %}
          <div class="txt_field">
              <input type="text" required name="username">
              <label class="label_class">Username</label>
          </div>
          <p></p>
            <div class="txt_field">
                <input type="password" required name="password">
                <label class="label_class">Password</label>
            </div><p></p>
            <input type="submit" value="Login"><p></p>
            <div class="signup_link"><a href="#">Forgot Password ?</a></div><p></p>
            <div class="signup_link">
                Not a member ? <a href={% url "forum:signup" %}><b>Signup</b></a>
            </div>
        </form>
    </div>
{% endblock content %}

forum/templates/forum/my_questions.html
{% extends "forum/base.html" %}

    
    {% load bootstrap4 %}
    {% load static %}
    
    {% block title %}My Questions{% endblock title %}



    {% block content %}
    {% bootstrap_messages %} 
    <h2>Posted By you</h2>
    {% for post in posts %}
<div class="question-container">
    <p style="color: #303030; margin-bottom: 0px;" ><i class="fas fa-user-circle" style="margin: 5px; font-size: large;"></i>{{ post.posted_by }}</p>
    
    <h5 style="color: blue; padding-left: 3px;"><a href={% url "forum:post_detail" slug=post.slug %}>{{ post.title }}</a>
        {% if post.solved %}
        <em style="color:green;">Solved</em>
    {% else %}
        <em style="color:red;">Unsolved</em>
    {% endif %}
    </h5>
    <p style="color: #acacac; padding-left: 3px;">
      {{ post.answerCount }} 
      {% if post.answerCount > 1 %}  answers
      {% else %}  answer
      {% endif %}
      
  
  </p>
  
  <div  style="margin-bottom:5px;"> 
    {% if post.solved is not True %}
    <a class="btn btn-outline-success" href={% url "forum:solved" slug=post.slug %}>Mark Solved</a>
{% else %}
<a class="btn btn-outline-warning" href={% url "forum:solved" slug=post.slug %}>Mark UnSolved</a>
{% endif %}
    <a class="btn btn-outline-danger" href={% url "forum:delete_post" slug=post.slug %} style="color:red;">Delete</a>
  </div>
  </div>
  {% endfor %}
  
    {% endblock content %}

forum/templates/forum/post_confirm_delete.html
{% extends "forum/base.html" %}
{% load bootstrap4 %}
{% load static %}


{% block content %}
<form method="post">{% csrf_token %}
     
 
 
    <p>Are you sure you want to delete <strong>"{{ object }}"</strong>?</p>
     
     
     
        <input type="submit" value="Confirm" class="btn btn-danger">
    </form>
{% endblock %}